---
- name: Deploy saya-today-web Docker Container
  hosts: all
  remote_user: svc_github

  tasks:
  - name: Deploy saya-today-web Docker Container
    community.docker.docker_container:
      name: "{{ saya_today_web.name }}"
      hostname: "{{ saya_today_web.hostname }}"
      image: "ghcr.io/sayaandy/saya-today-web:{{ saya_today_web.tag }}"
      env:
        B2_KEY_ID: "{{ saya_today_web.b2.key_id }}"
        B2_APPLICATION_KEY: "{{ saya_today_web.b2.application_key }}"
      network_mode: caddy
      networks:
        - name: caddy
          ipv4_address: "{{ saya_today_web.ipv4_address }}"
      restart_policy: unless-stopped
    no_log: true
...
