logLevel: debug
blogPages:
  storage:
    type: b2
    config:
      bucketName: sayana-pages
      region: eu-central-003
      prefix: 'stage-'
      keyID: '${B2_KEY_ID}'
      applicationKey: '${B2_APPLICATION_KEY}'
factGiver:
  storage:
    type: b2
    config:
      bucketName: sayana-pages
      region: eu-central-003
      prefix: ''
      keyID: '${B2_KEY_ID}'
      applicationKey: '${B2_APPLICATION_KEY}'
  factsFileName: 'facts-*.txt'
localePath: ./locale/
availableLanguages:
  - name: ru
    alt: Русский
    flag: https://f003.backblazeb2.com/file/sayana-static/flags/ru.svg
    locFile: localization.ru.yaml
  - name: en
    alt: English
    flag: https://f003.backblazeb2.com/file/sayana-static/flags/gb.svg
    locFile: localization.en.yaml
auth:
  db:
    type: sqlite3
    config:
      dsn: 'file:/data/auth.db?cache=private&mode=rwc&_locking_mode=EXCLUSIVE&_mutex=no&_auto_vacuum=2'
  salt: '${AUTH_SALT}'
mail:
  clientHost: '${FQDN}'
  mailHost: '${MAIL_HOST}'
  publicName: 'DEMO.SAYA.TODAY'
  mailAddress: '${MAIL_ADDRESS}'
  username: '${MAIL_USERNAME}'
  password: '${MAIL_PASSWORD}'
  salt: '${MAIL_SALT}'
