logLevel: debug
blogPages:
  storage:
    type: b2
    config:
      bucketName: sayana-pages
      region: eu-central-003
      prefix: ''
      keyID: '${B2_KEY_ID}'
      applicationKey: '${B2_APPLICATION_KEY}'
  availableLanguages:
    - name: ru
      alt: Русский
      flag: https://f003.backblazeb2.com/file/sayana-static/flags/ru.svg
    - name: en
      alt: English
      flag: https://f003.backblazeb2.com/file/sayana-static/flags/gb.svg
