logLevel: debug
blogPages:
  storage:
    type: b2
    config:
      bucketName: sayana-pages
      region: eu-central-003
      prefix: 'stage-'
      keyID: '${B2_KEY_ID}'
      applicationKey: '${B2_APPLICATION_KEY}'
localePath: ./locale/
availableLanguages:
  - name: ru
    alt: Русский
    flag: https://f003.backblazeb2.com/file/sayana-static/flags/ru.svg
    locFile: localization.ru.yaml
  - name: en
    alt: English
    flag: https://f003.backblazeb2.com/file/sayana-static/flags/gb.svg
    locFile: localization.en.yaml
auth:
  db:
    type: sqlite
    config:
      dsn: 'file:/data/auth.db?cache=shared&mode=memory'
  salt: '123'
