logLevel: debug
endpoint:
  type: unix
  config:
    path: "/etc/sayauz/stage.socket"
    chmod: '0666'
blogPages:
  storage:
    type: s3
    config:
      bucketName: sayauz-pages
      region: kz1
      prefix: "stage-"
      endpoint: "https://storage.yandexcloud.kz"
      usePathStyle: true
      accessKeyID: "${S3_ACCESS_KEY_ID}"
      secretAccessKey: "${S3_SECRET_ACCESS_KEY}"
factGiver:
  storage:
    type: s3
    config:
      bucketName: sayauz-pages
      region: kz1
      prefix: ""
      endpoint: "https://storage.yandexcloud.kz"
      usePathStyle: true
      accessKeyID: "${S3_ACCESS_KEY_ID}"
      secretAccessKey: "${S3_SECRET_ACCESS_KEY}"
  factsFileName: "facts-*.txt"
localePath: ./locale/
availableLanguages:
  - name: ru
    alt: Русский
    flag: https://cdn.saya.uz/stats/flags/ru.svg
    locFile: localization.ru.yaml
  - name: en
    alt: English
    flag: https://cdn.saya.uz/stats/flags/gb.svg
    locFile: localization.en.yaml
auth:
  db:
    type: sqlite3
    config:
      dsn: "file:/data/auth.db?cache=private&mode=rwc&_locking_mode=EXCLUSIVE&_mutex=no&_auto_vacuum=2&_journal_mode=WAL"
  salt: "${AUTH_SALT}"
mail:
  clientHost: "${FQDN}"
  mailHost: "${MAIL_HOST}"
  publicName: "STAGE.SAYA.UZ"
  mailAddress: "${MAIL_ADDRESS}"
  username: "${MAIL_USERNAME}"
  password: "${MAIL_PASSWORD}"
  salt: "${MAIL_SALT}"
  trigger:
    onNewPost: "0/3 * * * *"
canonicalEndpoint: "https://${FQDN}"
photoStorage:
  full:
    baseUrl: https://cdn.saya.uz/photos/jpeg-full/%s
  webp:
    baseUrl: https://cdn.saya.uz/photos/webp-full/%s.webp
  thumbnail1600p:
    baseUrl: https://cdn.saya.uz/photos/webp-1600p/%s.webp
  thumbnail1200p:
    baseUrl: https://cdn.saya.uz/photos/webp-1200p/%s.webp
  thumbnail800p:
    baseUrl: https://cdn.saya.uz/photos/webp-800p/%s.webp
  thumbnail560p:
    baseUrl: https://cdn.saya.uz/photos/webp-560p/%s.webp
  thumbnail320p:
    baseUrl: https://cdn.saya.uz/photos/webp-320p/%s.webp
  homePageGifs:
    baseUrl: https://cdn.saya.uz/stats/home-page-gifs/otter-%s.gif
    indexes: ["1", "2", "3"]
staticStorage:
  baseUrl: https://cdn.saya.uz/stats
  map:
    baseUrl: https://cdn.saya.uz/map
    pmTiles: global.pmtiles
allowOrigins:
  - https://cdn.saya.uz
